package np.bill

import np.bill.core.invoice.LineInput
import np.bill.core.invoice.computeInvoice
import np.bill.core.money.amountInWords
import np.bill.core.money.formatPaisa
import np.bill.core.money.formatQuantity
import np.bill.core.nepali.BsCalendar
import np.bill.util.Iso8601
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * The device and the server have to agree, to the paisa and to the day.
 *
 * An offline bill is printed from the device's arithmetic and its calendar, and the
 * server re-checks both when the bill finally syncs; a disagreement means a bill that is
 * already in a customer's hand gets refused. These expectations were generated by running
 * the server's own `computeInvoice`, `amountInWords` and `toBsString` over the cases
 * below, so this test fails the moment the two implementations drift.
 */
class ServerParityTest {

  @Test
  fun `case 1 totals the way the server totals it`() {
    val totals = computeInvoice(
      lines = listOf(
      LineInput(description = "a", unit = "kg", quantityMilli = 2000, unitPricePaisa = 12500, discountPaisa = 0, vatApplicable = true),
      ),
      invoiceDiscountPaisa = 0,
      vatRateBp = 1300,
    )

    assertEquals(25000L, totals.subTotalPaisa)
    assertEquals(0L, totals.discountPaisa)
    assertEquals(25000L, totals.taxableAmountPaisa)
    assertEquals(0L, totals.nonTaxableAmountPaisa)
    assertEquals(3250L, totals.vatAmountPaisa)
    assertEquals(28250L, totals.totalPaisa)
    assertEquals("Rupees Two Hundred Eighty Two and Fifty Paisa Only", amountInWords(totals.totalPaisa))
  }
  @Test
  fun `case 2 totals the way the server totals it`() {
    val totals = computeInvoice(
      lines = listOf(
      LineInput(description = "a", unit = "pcs", quantityMilli = 1000, unitPricePaisa = 3333, discountPaisa = 0, vatApplicable = true),
      LineInput(description = "b", unit = "pcs", quantityMilli = 1000, unitPricePaisa = 3333, discountPaisa = 0, vatApplicable = true),
      LineInput(description = "c", unit = "pcs", quantityMilli = 1000, unitPricePaisa = 3334, discountPaisa = 0, vatApplicable = true),
      ),
      invoiceDiscountPaisa = 1000,
      vatRateBp = 1300,
    )

    assertEquals(10000L, totals.subTotalPaisa)
    assertEquals(1000L, totals.discountPaisa)
    assertEquals(9000L, totals.taxableAmountPaisa)
    assertEquals(0L, totals.nonTaxableAmountPaisa)
    assertEquals(1170L, totals.vatAmountPaisa)
    assertEquals(10170L, totals.totalPaisa)
    assertEquals("Rupees One Hundred One and Seventy Paisa Only", amountInWords(totals.totalPaisa))
  }
  @Test
  fun `case 3 totals the way the server totals it`() {
    val totals = computeInvoice(
      lines = listOf(
      LineInput(description = "a", unit = "kg", quantityMilli = 2500, unitPricePaisa = 9999, discountPaisa = 250, vatApplicable = true),
      LineInput(description = "b", unit = "pkt", quantityMilli = 1000, unitPricePaisa = 3000, discountPaisa = 0, vatApplicable = false),
      ),
      invoiceDiscountPaisa = 777,
      vatRateBp = 1300,
    )

    assertEquals(27748L, totals.subTotalPaisa)
    assertEquals(777L, totals.discountPaisa)
    assertEquals(24056L, totals.taxableAmountPaisa)
    assertEquals(2915L, totals.nonTaxableAmountPaisa)
    assertEquals(3127L, totals.vatAmountPaisa)
    assertEquals(30098L, totals.totalPaisa)
    assertEquals("Rupees Three Hundred and Ninety Eight Paisa Only", amountInWords(totals.totalPaisa))
  }
  @Test
  fun `case 4 totals the way the server totals it`() {
    val totals = computeInvoice(
      lines = listOf(
      LineInput(description = "a", unit = "pcs", quantityMilli = 333, unitPricePaisa = 100000, discountPaisa = 0, vatApplicable = true),
      ),
      invoiceDiscountPaisa = 0,
      vatRateBp = 0,
    )

    assertEquals(33300L, totals.subTotalPaisa)
    assertEquals(0L, totals.discountPaisa)
    assertEquals(33300L, totals.taxableAmountPaisa)
    assertEquals(0L, totals.nonTaxableAmountPaisa)
    assertEquals(0L, totals.vatAmountPaisa)
    assertEquals(33300L, totals.totalPaisa)
    assertEquals("Rupees Three Hundred Thirty Three Only", amountInWords(totals.totalPaisa))
  }
  @Test
  fun `case 5 totals the way the server totals it`() {
    val totals = computeInvoice(
      lines = listOf(
      LineInput(description = "a", unit = "ltr", quantityMilli = 1500, unitPricePaisa = 7777, discountPaisa = 0, vatApplicable = true),
      LineInput(description = "b", unit = "ltr", quantityMilli = 2500, unitPricePaisa = 7777, discountPaisa = 100, vatApplicable = true),
      LineInput(description = "c", unit = "pcs", quantityMilli = 7000, unitPricePaisa = 1, discountPaisa = 0, vatApplicable = false),
      ),
      invoiceDiscountPaisa = 12345,
      vatRateBp = 1300,
    )

    assertEquals(31016L, totals.subTotalPaisa)
    assertEquals(12345L, totals.discountPaisa)
    assertEquals(18668L, totals.taxableAmountPaisa)
    assertEquals(3L, totals.nonTaxableAmountPaisa)
    assertEquals(2427L, totals.vatAmountPaisa)
    assertEquals(21098L, totals.totalPaisa)
    assertEquals("Rupees Two Hundred Ten and Ninety Eight Paisa Only", amountInWords(totals.totalPaisa))
  }

  @Test
  fun `money formats the Nepali way`() {
    assertEquals("0.00", formatPaisa(0L))
    assertEquals("0.05", formatPaisa(5L))
    assertEquals("0.99", formatPaisa(99L))
    assertEquals("1.00", formatPaisa(100L))
    assertEquals("123.45", formatPaisa(12345L))
    assertEquals("1,000.00", formatPaisa(100000L))
    assertEquals("12,34,567.89", formatPaisa(123456789L))
    assertEquals("1,00,00,000.00", formatPaisa(1000000000L))
    assertEquals("-250.50", formatPaisa(-25050L))
  }

  @Test
  fun `amounts spell out on the Nepali scale`() {
    assertEquals("Rupees Zero Only", amountInWords(0L))
    assertEquals("Rupees Zero and Five Paisa Only", amountInWords(5L))
    assertEquals("Rupees Zero and Ninety Nine Paisa Only", amountInWords(99L))
    assertEquals("Rupees One Only", amountInWords(100L))
    assertEquals("Rupees One Hundred Twenty Three and Forty Five Paisa Only", amountInWords(12345L))
    assertEquals("Rupees One Thousand Only", amountInWords(100000L))
    assertEquals("Rupees Twelve Lakh Thirty Four Thousand Five Hundred Sixty Seven and Eighty Nine Paisa Only", amountInWords(123456789L))
    assertEquals("Rupees One Crore Only", amountInWords(1000000000L))
    assertEquals("Minus Rupees Two Hundred Fifty and Fifty Paisa Only", amountInWords(-25050L))
  }

  @Test
  fun `quantities keep their thousandths`() {
    assertEquals("0.001", formatQuantity(1L))
    assertEquals("0.5", formatQuantity(500L))
    assertEquals("1", formatQuantity(1000L))
    assertEquals("2.5", formatQuantity(2500L))
    assertEquals("123.456", formatQuantity(123456L))
  }

  @Test
  fun `Bikram Sambat dates and fiscal years match the server`() {
    assertEquals("2083-05-13", BsCalendar.toBs(Iso8601.parse("2026-08-29T09:15:00Z")!!).toString())
    assertEquals("2083.084", BsCalendar.fiscalYearFor(Iso8601.parse("2026-08-29T09:15:00Z")!!))
    assertEquals("2083-04-01", BsCalendar.toBs(Iso8601.parse("2026-07-16T18:20:00Z")!!).toString())
    assertEquals("2083.084", BsCalendar.fiscalYearFor(Iso8601.parse("2026-07-16T18:20:00Z")!!))
    assertEquals("2083-03-32", BsCalendar.toBs(Iso8601.parse("2026-07-16T18:10:00Z")!!).toString())
    assertEquals("2082.083", BsCalendar.fiscalYearFor(Iso8601.parse("2026-07-16T18:10:00Z")!!))
    assertEquals("2082-01-01", BsCalendar.toBs(Iso8601.parse("2025-04-13T23:00:00Z")!!).toString())
    assertEquals("2081.082", BsCalendar.fiscalYearFor(Iso8601.parse("2025-04-13T23:00:00Z")!!))
    assertEquals("2080-09-16", BsCalendar.toBs(Iso8601.parse("2024-01-01T00:00:00Z")!!).toString())
    assertEquals("2080.081", BsCalendar.fiscalYearFor(Iso8601.parse("2024-01-01T00:00:00Z")!!))
    assertEquals("2083-09-16", BsCalendar.toBs(Iso8601.parse("2026-12-31T18:14:00Z")!!).toString())
    assertEquals("2083.084", BsCalendar.fiscalYearFor(Iso8601.parse("2026-12-31T18:14:00Z")!!))
  }

  @Test
  fun `the fiscal year turns over on Shrawan 1, not at the BS new year`() {
    // 2083-03-32 is the last day of Ashad and still the old year; the next day opens the new one.
    assertEquals("2082.083", BsCalendar.fiscalYearFor(np.bill.core.nepali.BsDate(2083, 3, 32)))
    assertEquals("2083.084", BsCalendar.fiscalYearFor(np.bill.core.nepali.BsDate(2083, 4, 1)))
  }
}
