/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as PrintInvoiceIdRouteImport } from './routes/print/$invoiceId'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as AuthAppCustomersRouteImport } from './routes/_auth/app/customers'
import { Route as AuthAppItemsRouteImport } from './routes/_auth/app/items'
import { Route as AuthAppReportsRouteImport } from './routes/_auth/app/reports'
import { Route as AuthAppSettingsRouteImport } from './routes/_auth/app/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppInvoicesIndexRouteImport } from './routes/_auth/app/invoices/index'
import { Route as AuthAppInvoicesInvoiceIdRouteImport } from './routes/_auth/app/invoices/$invoiceId'
import { Route as AuthAppInvoicesNewRouteImport } from './routes/_auth/app/invoices/new'
import { Route as ApiInvoicesInvoiceIdPdfRouteImport } from './routes/api/invoices/$invoiceId/pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const PrintInvoiceIdRoute = PrintInvoiceIdRouteImport.update({
  id: '/print/$invoiceId',
  path: '/print/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppCustomersRoute = AuthAppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppItemsRoute = AuthAppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppReportsRoute = AuthAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppSettingsRoute = AuthAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppInvoicesIndexRoute = AuthAppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppInvoicesInvoiceIdRoute =
  AuthAppInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppInvoicesNewRoute = AuthAppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiInvoicesInvoiceIdPdfRoute = ApiInvoicesInvoiceIdPdfRouteImport.update({
  id: '/api/invoices/$invoiceId/pdf',
  path: '/api/invoices/$invoiceId/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/onboarding': typeof AuthOnboardingRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/print/$invoiceId': typeof PrintInvoiceIdRoute
  '/app/customers': typeof AuthAppCustomersRoute
  '/app/items': typeof AuthAppItemsRoute
  '/app/reports': typeof AuthAppReportsRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/invoices/$invoiceId': typeof AuthAppInvoicesInvoiceIdRoute
  '/app/invoices/new': typeof AuthAppInvoicesNewRoute
  '/api/invoices/$invoiceId/pdf': typeof ApiInvoicesInvoiceIdPdfRoute
  '/app/invoices/': typeof AuthAppInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/print/$invoiceId': typeof PrintInvoiceIdRoute
  '/app/customers': typeof AuthAppCustomersRoute
  '/app/items': typeof AuthAppItemsRoute
  '/app/reports': typeof AuthAppReportsRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/invoices/$invoiceId': typeof AuthAppInvoicesInvoiceIdRoute
  '/app/invoices/new': typeof AuthAppInvoicesNewRoute
  '/api/invoices/$invoiceId/pdf': typeof ApiInvoicesInvoiceIdPdfRoute
  '/app/invoices': typeof AuthAppInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/print/$invoiceId': typeof PrintInvoiceIdRoute
  '/_auth/app/customers': typeof AuthAppCustomersRoute
  '/_auth/app/items': typeof AuthAppItemsRoute
  '/_auth/app/reports': typeof AuthAppReportsRoute
  '/_auth/app/settings': typeof AuthAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/invoices/$invoiceId': typeof AuthAppInvoicesInvoiceIdRoute
  '/_auth/app/invoices/new': typeof AuthAppInvoicesNewRoute
  '/api/invoices/$invoiceId/pdf': typeof ApiInvoicesInvoiceIdPdfRoute
  '/_auth/app/invoices/': typeof AuthAppInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/login'
    | '/signup'
    | '/print/$invoiceId'
    | '/app/customers'
    | '/app/items'
    | '/app/reports'
    | '/app/settings'
    | '/api/auth/$'
    | '/app/'
    | '/app/invoices/$invoiceId'
    | '/app/invoices/new'
    | '/api/invoices/$invoiceId/pdf'
    | '/app/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/login'
    | '/signup'
    | '/print/$invoiceId'
    | '/app/customers'
    | '/app/items'
    | '/app/reports'
    | '/app/settings'
    | '/api/auth/$'
    | '/app'
    | '/app/invoices/$invoiceId'
    | '/app/invoices/new'
    | '/api/invoices/$invoiceId/pdf'
    | '/app/invoices'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/app'
    | '/_auth/onboarding'
    | '/_guest/login'
    | '/_guest/signup'
    | '/print/$invoiceId'
    | '/_auth/app/customers'
    | '/_auth/app/items'
    | '/_auth/app/reports'
    | '/_auth/app/settings'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/app/invoices/$invoiceId'
    | '/_auth/app/invoices/new'
    | '/api/invoices/$invoiceId/pdf'
    | '/_auth/app/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  PrintInvoiceIdRoute: typeof PrintInvoiceIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInvoicesInvoiceIdPdfRoute: typeof ApiInvoicesInvoiceIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/print/$invoiceId': {
      id: '/print/$invoiceId'
      path: '/print/$invoiceId'
      fullPath: '/print/$invoiceId'
      preLoaderRoute: typeof PrintInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/customers': {
      id: '/_auth/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AuthAppCustomersRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/items': {
      id: '/_auth/app/items'
      path: '/items'
      fullPath: '/app/items'
      preLoaderRoute: typeof AuthAppItemsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/reports': {
      id: '/_auth/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthAppReportsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/settings': {
      id: '/_auth/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthAppSettingsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/invoices/': {
      id: '/_auth/app/invoices/'
      path: '/invoices'
      fullPath: '/app/invoices/'
      preLoaderRoute: typeof AuthAppInvoicesIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/invoices/$invoiceId': {
      id: '/_auth/app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/app/invoices/$invoiceId'
      preLoaderRoute: typeof AuthAppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/invoices/new': {
      id: '/_auth/app/invoices/new'
      path: '/invoices/new'
      fullPath: '/app/invoices/new'
      preLoaderRoute: typeof AuthAppInvoicesNewRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/invoices/$invoiceId/pdf': {
      id: '/api/invoices/$invoiceId/pdf'
      path: '/api/invoices/$invoiceId/pdf'
      fullPath: '/api/invoices/$invoiceId/pdf'
      preLoaderRoute: typeof ApiInvoicesInvoiceIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppCustomersRoute: typeof AuthAppCustomersRoute
  AuthAppItemsRoute: typeof AuthAppItemsRoute
  AuthAppReportsRoute: typeof AuthAppReportsRoute
  AuthAppSettingsRoute: typeof AuthAppSettingsRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppInvoicesInvoiceIdRoute: typeof AuthAppInvoicesInvoiceIdRoute
  AuthAppInvoicesNewRoute: typeof AuthAppInvoicesNewRoute
  AuthAppInvoicesIndexRoute: typeof AuthAppInvoicesIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppCustomersRoute: AuthAppCustomersRoute,
  AuthAppItemsRoute: AuthAppItemsRoute,
  AuthAppReportsRoute: AuthAppReportsRoute,
  AuthAppSettingsRoute: AuthAppSettingsRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppInvoicesInvoiceIdRoute: AuthAppInvoicesInvoiceIdRoute,
  AuthAppInvoicesNewRoute: AuthAppInvoicesNewRoute,
  AuthAppInvoicesIndexRoute: AuthAppInvoicesIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
  AuthOnboardingRoute: typeof AuthOnboardingRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
  AuthOnboardingRoute: AuthOnboardingRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  PrintInvoiceIdRoute: PrintInvoiceIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInvoicesInvoiceIdPdfRoute: ApiInvoicesInvoiceIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
